#!/bin/sh

# only at start
test "$1" != "start" && exit 0


amixer -c 0 sset HpSpeaker on
amixer -c 0 sset LINEOUT on
# this volume slider is inverted in the audio drivers on trimui. Value goes from 0 to 7. 0 means no attenuation (volume max)
amixer -c 0 sset Headphone 0
